export interface ICompany {
  id: string,
  code: string,
  name: string,
  stocks: number,
  eps: number,
  bps: number,
  devidend: number,
  buyPrice: number,
  totalProfit: number,
  bookValue: number,
  totalBuyPrice: number,
  profitYield: number,
  roe: number,
  per: number,
  pbr: number,
  uid: string,
}